# Generated by Django 4.2.7 on 2023-11-09 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('first_contact', models.DateField(default='')),
                ('origin_city', models.CharField(max_length=50)),
                ('origin_street', models.CharField(max_length=50)),
                ('origin_post_code', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=10)),
                ('contracting_date', models.DateField(default=None, null=True)),
                ('contracting_kind', models.CharField(choices=[('estimation', 'Kostenschätzung'), ('calculation', 'Kostenberechnung'), ('tender', 'Ausschreibung')], default='', max_length=20)),
                ('order_value', models.IntegerField(default='')),
                ('date_start', models.DateField(default=None, null=True)),
                ('date_end', models.DateField(default=None, null=True)),
                ('precessing_time', models.DurationField(default='')),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.client')),
                ('contractor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('shortage', models.CharField(default='', max_length=5)),
                ('processing_time', models.DurationField(default='')),
                ('date_start', models.DateField(default=None, null=True)),
                ('date_end', models.DateField(default=None, null=True)),
                ('features', models.CharField(default='', max_length=500)),
                ('client', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.client')),
                ('contract', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contract')),
                ('project_lead', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_projects', to=settings.AUTH_USER_MODEL)),
                ('project_team', models.ManyToManyField(default='', related_name='team_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('company', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.client')),
            ],
        ),
    ]
