# Generated by Django 4.2.7 on 2023-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hours',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
